# Generated by Django 4.1.2 on 2022-10-21 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Benefit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField()),
                ("recurrence", models.TextField()),
            ],
            options={
                "db_table": "benefit",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
            ],
            options={
                "db_table": "person",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Venue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
            ],
            options={
                "db_table": "venue",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="BenefitUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("usagetimestamp", models.DateTimeField(db_column="usageTimestamp")),
                (
                    "benefitid",
                    models.ForeignKey(
                        db_column="benefitId",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="core.benefit",
                    ),
                ),
                (
                    "personid",
                    models.ForeignKey(
                        db_column="personId",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="core.person",
                    ),
                ),
            ],
            options={
                "db_table": "benefit_usage",
                "managed": True,
            },
        ),
        migrations.AddField(
            model_name="benefit",
            name="venueid",
            field=models.ForeignKey(
                db_column="venueId",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="core.venue",
            ),
        ),
    ]
